railway/board/urls.py
urlpatterns = [
    
]

railway/railway/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


from rest_framework import routers
from api import views as vapi
from rails import views as vrails

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'profiles', vapi.ProfileViewset)
router.register(r'tickets', vapi.TicketViewset)
router.register(r'trains', vapi.TrainViewset)
router.register(r'carriages', vapi.CarriageViewset)
router.register(r'cities', vapi.CityViewset)
router.register(r'places', vapi.PlacesViewset)
router_rails = routers.DefaultRouter(trailing_slash=False)

urlpatterns = [
    # Админка
    path('admin/', admin.site.urls, name='admin'),
    
    # # API
    path('api/v1/', include(router.urls)),
    path('api-auth', include('rest_framework.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^api/auth/', include('djoser.urls.authtoken')),
    path('board/', include('board.urls')),
    
    # Сайт
    path('', vrails.MainView.as_view(), name='index'),
    path('profile/', vrails.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/', vrails.UpdateProfile.as_view(), name='update_profile'),
    path('trains/', vrails.TrainsView.as_view(), name='trains'),
    path('train/<slug:slug>/', vrails.TrainDetailView.as_view(), name='train'),
    path('buy/<int:pk>/', vrails.BuyTicket.as_view(), name='buy'),
    path('login/', vrails.LoginView.as_view(), name='login'),
    path('logout/', vrails.logout_user, name='logout'),
    path('reg/', vrails.RegView.as_view(), name='reg'),
]
# handler404 = "rails.views.page_not_found_view"

railway/rails/forms.py
import unicodedata
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX, identify_hasher,
)
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed

from .models import *
from user.models import User

UserModel = get_user_model()

class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize('NFKC', super().to_python(value))

    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            'autocapitalize': 'none',
            'autocomplete': 'username',
        }

class MainForm(forms.Form):
    start_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город отправления', required=True)
    end_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город прибытия', required=True)
    start_date = forms.DateField(label='Дата отправления', required=True)

    def clean_start_date_date(self):
        data = self.cleaned_data['start_date']
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - start_date in past'))
        if data > datetime.date.today() + datetime.timedelta(weeks=8):
            raise ValidationError(_('Invalid date - start_date more than 8 weeks ahead'))

        return data


class LoginForm(forms.ModelForm):
    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(email)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwarks):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwarks)
        self.email_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        email_max_length = self.email_field.max_length or 254
        self.fields['email'].max_length = email_max_length
        self.fields['email'].widget.attrs['maxlength'] = email_max_length
        self.fields['email'].label = 'E-mail'
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)
        self.fields['password'].label = 'Пароль'


    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, email):
        if not email.is_active:
            raise ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'email': self.email_field.verbose_name},
        )

class LoginForm2(forms.Form):
    email = UsernameField(widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )
    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(email)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        # self.email = UsernameField(widget=forms.TextInput(attrs={'autofocus': True}))
        # self.password = forms.CharField(
        #     label=_("Password"),
        #     strip=False,
        #     widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
        # )
        # self.request = request
        # self.user_cache = None
        # super().__init__(*args, **kwarks)
        # self.fields['email'].label = 'E-mail'
        # self.fields['password'].label = 'Пароль'
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        self.email_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        email_max_length = self.email_field.max_length or 254
        self.fields['email'].max_length = email_max_length
        self.fields['email'].widget.attrs['maxlength'] = email_max_length
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)

    # class Meta:
    #     model = User
    #     fields = ['email', 'password']

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, email):
        if not email.is_active:
            raise ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'email': self.email_field.verbose_name},
        )

class RegForm(forms.ModelForm):
    def __init__(self, *args, **kwarks):
        super().__init__(*args, **kwarks)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs['autofocus'] = True
        self.fields['email'].label = 'E-mail'
        self.fields['password'].label = 'Пароль'

    class Meta:
        model = User
        fields = ['email', 'password']

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get('password')
        if password:
            password_validation.validate_password(password, self.instance)

    def save(self, commit=True):
        email = super().save(commit=False)
        email.set_password(self.cleaned_data["password"])
        if commit:
            email.save()
        return email
        
class BuyForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['user','train','carriage', 'places']

    

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','third_name']

    

railway/railway/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/5.0.0/css/bootstrap-theme.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid pr-2 d-flex justify-content-between text-aligh-center">
          <a class="navbar-brand" href="{% url 'index' %}">
            <h4>RailWay</h4>
          </a>

          <div class="btn btn-danger">
            {% if request.user.is_authenticated %}
            {% if request.user.is_staff %}
            <a style="color: white; text-decoration: none;" href="/admin/" role="button">Администрирование</a>&nbsp;|&nbsp;
            {% endif%}
            <a style="color: white; text-decoration: none;" href="{% url 'profile' %}" role="button">{{request.user.email}}</a>&nbsp;|&nbsp;<a style="color: white; text-decoration: none;" href="{% url 'logout' %}" role="button">Выйти</a>
            {% else %}
            <a style="color: white; text-decoration: none;" href="{% url 'login' %}" role="button">Войти</a>&nbsp;|&nbsp;<a style="color: white; text-decoration: none;" href="{% url 'reg' %}" role="button">Регистрация</a>
            {% endif %}
          </div>
        </div>

      </nav>

    <main style="padding-top: 80px;padding-bottom: 30px;">
        {% block content %}
        
        {% endblock %}
    </main>
    <nav class="nav fixed-bottom navbar-light bg-light">
        <div class="container-md container-fluid">
            <ul class="nav justify-content-center">
                <li class="nav-item">
                    <span class="navbar-brand p-4 h2">&copy;Maxim Timofeev, 2022</span>
                  <!-- <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">&copy;Maxim Timofeev, 2022</a> -->
                </li>
            </ul>
        </div>
    </nav>
    
</body>
</html>

railway/railway/templates/index.html
{% extends 'base.html' %}

{% block title %}RailWay{% endblock %}
 
{% block content %}

<div class="container-lg  p-4">
    <h2 class="p-3">Купить билет</h2>

    <div class="city_group">
        <form action="{% url 'trains' %}" method="get">
            <div class="input-group m-3">
                <label class="input-group-text" for="id_start_city">{{form.start_city.label}}</label>
                <select name="start_city" required class="form-select p-2" id="inputGroupSelect01 id_start_city">
                <option value selected>Откуда</option>
                {% for city in city_list %}
                    <option value="{{city.id}}">{{city.name}}</option>
                {% endfor %}
                </select>
            </div>
        
            <div class="input-group m-3">
                <label class="input-group-text" for="id_end_city">{{form.end_city.label}}</label>
                <select name="end_city" required class="form-select p-2" id="inputGroupSelect02 id_end_city">
                <option value selected>Куда</option>
                {% for city in city_list %}
                    <option value="{{city.id}}">{{city.name}}</option>
                {% endfor %}
                </select>
            </div>

            <div class="input-group m-3">
                <label class="input-group-text" for="id_start_date">{{form.start_date.label}}</label>
                <input name="start_date" required class="p-2" type="date"  min="2022-12-23" id="inputGroupSelect03 id_start_date">
            </div>
            <script>
                var date = new Date();
                const now = date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2);
                const input = document.getElementsByName("start_date");
                console.log(input);
                input[0].setAttribute('min', now);
            
            </script>
            <button class="btn btn-danger m-3" type="submit">Найти</button>
        </form>
    </div>
</div>



{% endblock %}