railway/board/urls.py
urlpatterns = [
    
]

railway/railway/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


from rest_framework import routers
from api import views as vapi
from rails import views as vrails

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'profiles', vapi.ProfileViewset)
router.register(r'tickets', vapi.TicketViewset)
router.register(r'trains', vapi.TrainViewset)
router.register(r'carriages', vapi.CarriageViewset)
router.register(r'cities', vapi.CityViewset)
router.register(r'places', vapi.PlacesViewset)
router_rails = routers.DefaultRouter(trailing_slash=False)

urlpatterns = [
    # Админка
    path('admin/', admin.site.urls, name='admin'),
    
    # # API
    path('api/v1/', include(router.urls)),
    path('api-auth', include('rest_framework.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path(r'^api/auth/', include('djoser.urls.authtoken')),
    path('board/', include('board.urls')),
    
    # Сайт
    path('', vrails.MainView.as_view(), name='index'),
    path('profile/', vrails.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/', vrails.UpdateProfile.as_view(), name='update_profile'),
    path('trains/', vrails.TrainsView.as_view(), name='trains'),
    path('train/<slug:slug>/', vrails.TrainDetailView.as_view(), name='train'),
    path('buy/<int:pk>/', vrails.BuyTicket.as_view(), name='buy'),
    path('login/', vrails.LoginView.as_view(), name='login'),
    path('logout/', vrails.logout_user, name='logout'),
    path('reg/', vrails.RegView.as_view(), name='reg'),
]
# handler404 = "rails.views.page_not_found_view"

railway/rails/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Train(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    start_time = models.TimeField()
    end_time = models.TimeField()
    
    start_date = models.DateField()
    end_date = models.DateField()

    start_city = models.ForeignKey('City', related_name='trains_start', on_delete=models.DO_NOTHING)
    end_city = models.ForeignKey('City', related_name='trains_end', on_delete=models.DO_NOTHING)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('train', kwargs={'train_slug': self.slug})

class Ticket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='tickets'
    )
    train = models.ForeignKey('Train', related_name='tickets', on_delete=models.DO_NOTHING)
    carriage = models.ForeignKey('Carriage', related_name='tickets', on_delete=models.DO_NOTHING)

    places = models.ForeignKey('Places', related_name='tickets', on_delete=models.DO_NOTHING)

    def __str__(self) -> str:
        return self.train.name + '-' + str(self.places)

class City(models.Model):
    name = models.CharField(max_length=255, db_index=True)

    def __str__(self) -> str:
        return self.name

class Carriage(models.Model):
    pls = [
        ('RS','Плацкарт'),
        ('CP','Купе'),
        ('SW','СВ')
    ]

    train = models.ForeignKey('Train', related_name='carriages', on_delete=models.CASCADE)

    number = models.IntegerField()
    place_type = models.CharField(
        max_length=2,
        choices=pls
    )
    
    def __str__(self) -> str:
        return self.train.name + '-' + str(self.number) + '-' + self.get_place_type_display()
    

class Places(models.Model):
    carriage = models.ForeignKey('Carriage', related_name='places', on_delete=models.CASCADE)
    number = models.IntegerField()
    status = models.BooleanField(default=True)

    def __str__(self) -> str:
        return str(self.number) + '-' + str(self.carriage.number)

railway/user/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class MyUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email: 
            raise ValueError("Вы не ввели Email")
        if not password: 
            raise ValueError("Вы не ввели пароль")
        user = self.model(
            email=self.normalize_email(email),
            # password=password
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password):
        return self._create_user(email, password)
 
    # Делаем метод для создание админа сайта
    def create_superuser(self, email, password):
        return self._create_user(email, password, is_staff=True, is_superuser=True)

class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True, unique=True) # Идентификатор
    email = models.EmailField(max_length=100, unique=True) # Email
    password = models.CharField(max_length=100)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    third_name = models.CharField(max_length=100)
    
    is_active = models.BooleanField(default=True) # Статус активации
    is_staff = models.BooleanField(default=False) # Статус админа


    USERNAME_FIELD = 'email' # Идентификатор для обращения 
    REQUIRED_FIELDS = [] # Список имён полей для Superuser
 
    objects = MyUserManager() # Добавляем методы класса MyUserManager

    def __str__(self) -> str:
        return self.email

railway/railway/templates/railway/buy.html
{% extends 'base.html' %}
 
{% block title %}RailWay - {{train.name}}{% endblock %}
 
{% block content %}
<div class="card mb-3">
    <h3 class="card-header">Поезд <span class="badge bg-danger">{{request.train.name}}</span></h3>
    <div class="card-body">
        <div class="mb-3 d-flex">
            <div class="container-fluid p-3">
                <h5 class="card-title">Время</h5>
                <div class="">
                    <p class="card-text">Отправление: {{train.start_date}} - {{train.start_time}}</p>
                    <p class="card-text">Прибытие: {{train.end_date}} - {{train.end_time}}</p>
                </div>
            </div>
            <div class="container-fluid">
                <h5 class="card-title">Место</h5>
                <p class="card-text">Отправление: {{train.start_city}}</p>
                <p class="card-text">Прибытие: {{train.end_city}}</p>
            </div>
        </div>

        <div class="mb-3 d-flex">
            <form action="" method="post">
                {% csrf_token %}
                <input type="hidden" id="id_train" name="train">
                <div class="input-group m-3">
                    <label class="input-group-text" for="id_carriage">Вагон</label>
                    <select id="inputGroupSelect01 id_carriage" name="carriage" class="form-select" aria-label="Default select example">
                        <option selected>Выберите вагон</option>
                        {% for carriage in train.carriages.all %}
                        
                        <option value="{{car.id}}">{{carriage.number}} - {{carriage.place_type}}</option>
                        
                        {% endfor %}
                      </select>
                </div>
                <div class="input-group m-3">
                    <label class="input-group-text" for="id_places">Место</label>
                    <select id="inputGroupSelect02 id_places" name="places" class="form-select" aria-label="Default select example">
                        <option selected>Выберите место</option>
                        {% for carriage in train.carriages.all %}
                            {% for place in carriage.places.all %}
                                {% if place.status %}
                                    <option value="{{car.id}}">{{place.number}}</option>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                      </select>
                </div>

                <button class="btn btn-danger m-3"  type="submit">Купить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

railway/railway/templates/railway/login.html
{% extends 'base.html' %}
 
{% block title %}RailWay - Login{% endblock %}

{% block content %}

<div class="container-lg">
    <h2 class="m-3">Вход в аккаунт</h2>

    <form action="{% url 'login' %}" method="post">
    {% csrf_token %}

    <div class="form-floating m-3">
        <input type="email" name="email" class="form-control" id="floatingInput id_email" max_length="100" placeholder="name@example.com">
        <label for="floatingInput">{{form.email.label}}</label>
    </div>
    <div class="form-floating m-3">
        <input type="password" name="password" class="form-control" id="floatingPassword id_password" max_length="100" placeholder="Password" required>
        <label for="floatingPassword">{{form.password.label}}</label>
    </div>

    <!-- {{ form.as_p }} -->
    <!-- is-invalid -->
    <button class="btn btn-danger m-3" type="submit">Войти</button>
    </form>
</div>

{% endblock %}

railway/railway/templates/railway/profile.html
{% extends 'base.html' %}
 
{% block title %}RailWay - Profile{% endblock %}

{% block content %}

<div class="container-lg mb-5">
    <h2 class="m-3">Аккаунт</h2>

    <form action="{% url 'update_profile' request.user.id %}" method="post">
    {% csrf_token %}

    <div class="input-group m-3">
        <label class="input-group-text" for="id_last_name">Фамилия&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
        {% if request.user.last_name %}
        <input name="last_name" value="{{ request.user.last_name }}" required class="form-control p-2" type="text" id="id_last_name">
        {% else %}
        <input name="last_name" required class="form-control p-2" type="text" id="id_last_name">
        {% endif%}
    </div>
    <div class="input-group m-3">
        <label class="input-group-text" for="id_first_name">Имя&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
        {% if request.user.first_name %}
        <input name="first_name" value="{{ request.user.first_name }}" required class="form-control p-2" type="text" id="id_first_name">
        {% else %}
        <input name="first_name" required class="form-control p-2" type="text" id="id_first_name">
        {% endif%}
    </div>
    <div class="input-group m-3">
        <label class="input-group-text" for="id_third_name">Отчество&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
        <input name="third_name" required {% if request.user.third_name %} value="{{ request.user.third_name }}" {% endif%} class="form-control p-2" type="text" id="id_third_name">
    </div>
    <div class="input-group m-3">
        <label class="input-group-text" for="id_email">E-mail&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
        <input style="background-color: #fff; color: #000;" disabled value="{{ request.user.email }}" class="form-control p-2" type="email" id="id_email">
    </div>
    <!-- <div class="input-group m-3">
        <label class="input-group-text" for="id_password">Пароль&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
        <input name="password" class="form-control p-2" type="password" id="id_password">
    </div> -->
    <button class="btn btn-danger m-3" type="submit">Сохранить</button>
    </form>
</div>

<div class="container-lg">
    <h2 class="m-3">Билеты</h2>
    {% for t in request.user.tickets.all %}
    <div class="card mb-3">
        <h3 class="card-header">Поезд <span class="badge bg-danger">{{t.train.name}}</span></h3>
        <div class="card-body">
            <div class="mb-3 d-flex">
                <div class="container-fluid p-3">
                    <h5 class="card-title">Время</h5>
                    <div class="">
                        <p class="card-text">Отправление:<br>{{t.train.start_date}}<br>{{t.train.start_time}}</p>
                        <p class="card-text">Прибытие:<br>{{t.train.end_date}}<br>{{t.train.end_time}}</p>
                    </div>
                </div>
                <div class="container-fluid">
                    <h5 class="card-title">Место</h5>
                    <p class="card-text">Отправление: {{t.train.start_city}}</p>
                    <p class="card-text">Прибытие: {{t.train.end_city}}</p>
                </div>
            </div>
            <div class="mb-3 d-flex">
                <div class="container-fluid p-3">
                    <h5 class="card-title">Вагон</h5>
                    <p class="card-text">Номер: {{t.carriage.number}}<br>Тип: {{t.carriage.place_type}}</p>
                </div>
                <div class="container-fluid">
                    <h5 class="card-title">Место</h5>
                    <p class="card-text">Номер: {{t.places.number}}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

railway/railway/templates/railway/registration.html
{% extends 'base.html' %}
 
{% block title %}RailWay - Регистрация{% endblock %}

{% block content %}

<div class="container-lg">
    <h2 class="m-3">Регистрация</h2>

    <form method="post">
    {% csrf_token %}

    <div class="form-floating m-3">
        <input type="email" name="email" class="form-control" id="floatingInput id_email" max_length="100" placeholder="name@example.com">
        <label for="floatingInput">{{form.email.label}}</label>

    </div>
    <div class="form-floating m-3">
        <input type="password" name="password" class="form-control" id="floatingPassword id_password" max_length="100" placeholder="Password" required>
        <label for="floatingPassword">{{form.password.label}}</label>
    </div>

    <button class="btn btn-danger m-3" type="submit">Зарегистрироваться</button>
    </form>
</div>

{% endblock %}

railway/railway/templates/railway/train.html
{% extends 'base.html' %}
 
{% block title %}RailWay - {{train.name}}{% endblock %}
 
{% block content %}
<div class="card mb-3">
    <h3 class="card-header">Поезд <span class="badge bg-danger">{{train.name}}</span></h3>
    <div class="card-body">
        <div class="mb-3 d-flex">
            <div class="container-fluid p-3">
                <h5 class="card-title">Время</h5>
                <div class="">
                    <p class="card-text">Отправление: {{train.start_date}} - {{train.start_time}}</p>
                    <p class="card-text">Прибытие: {{train.end_date}} - {{train.end_time}}</p>
                </div>
            </div>
            <div class="container-fluid">
                <h5 class="card-title">Место</h5>
                <p class="card-text">Отправление: {{train.start_city}}</p>
                <p class="card-text">Прибытие: {{train.end_city}}</p>
            </div>
        </div>

        <div class="mb-3 d-flex">
            <form action="{% url 'buy' train.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{train.id}}" name="train">
                <input type="hidden" value="{{request.user.id}}" name="user">
                
                <div class="input-group m-3">
                    <label class="input-group-text" for="id_carriage">Вагон</label>
                    <select required id="inputGroupSelect01 id_carriage" name="carriage" class="car form-select" aria-label="Default select example">
                        <option selected>Выберите вагон</option>
                        
                        {% for carriage in train.carriages.all %}
                        <option value="{{carriage.id}}">{{carriage.number}} - {{carriage.place_type}}</option>
                        {% endfor %}
                      </select>
                </div>
                <divsel  id="sel {{carriage.id}}_select" sel class="input-group m-3">
                    <label class="input-group-text" for="inputGroupSelect02">Место</label>
                    <select id="inputGroupSelect02" required name="places" class="form-select" aria-label="Default select example">
                        <option selected>Выберите место</option>
                        
                            {% for carriage in train.carriages.all %}
                        
                            {% for place in carriage.places.all %}
                                {% if place.status and place.carriage.id == carriage.id %}
                                    <option id="change_{{place.id}}" value="{{place.id}}">{{place.number}} - {{carriage.number}}</option>
                                {% endif %}
                            {% endfor %}
                        
                            {% endfor %}
                      </select>
                </divsel>
                <!-- <input type="" value="" id="id_places" name=""> -->

                <button class="btn btn-danger m-3"  type="submit">Купить</button>
            </form>
        </div>
        <!-- <script type="text/javascript">
            let sel_elements = document.getElementsByTagName('divsel')
            console.log(sel_elements);
            let select = document.getElementsByClassName('car')[0];
            let num = 0;
            let inp = document.getElementById("id_places");


            select.addEventListener('change', function(){  
                sel_elements[num].setAttribute('hidden', 'hidden');
                var getValue = this.value - 1;
                sel_elements[getValue].removeAttribute('hidden');
                sel_elements[getValue].addEventListener('change', function(){
                    let items = [];
                    // const inputGroupSelect02 = document.getElementById("inputGroupSelect02").text;
                    for (const child of inputGroupSelect02.children) {
                        items.push(child)
                    }
                    let v = items[-1];
                    console.log(v)
                    inp.setAttribute('value', v)
                });
                num = getValue;
            });
            
            // let items = [];
            // const inputGroupSelect02 = document.getElementById("inputGroupSelect02");
            // for (const child of inputGroupSelect02.children) {
            //     console.log(child.tagName); 
            //     items.push(child);  
            //     console.log(items);
            // }
        </script> -->
        <!-- <a href="/train/{{train.slug}}" class="btn btn-danger">Купить</a> -->
    </div>
</div>
{% endblock %}

railway/railway/templates/railway/trains_list.html
{% extends 'base.html' %}
 
{% block title %}RailWay{% endblock %}

{% block content %}
<div class="container-fluid ">
    {% if trains_list %}
    {% for train in trains_list %}
    <div class="card mb-3">
        <h3 class="card-header">Поезд <span class="badge bg-danger">{{train.name}}</span></h3>
        <div class="card-body">
            <div class="mb-3 d-flex">
                <div class="container-fluid p-3">
                    <h5 class="card-title">Время</h5>
                    <div class="">
                        <p class="card-text">Отправление:<br>{{train.start_date}}<br>{{train.start_time}}</p>
                        <p class="card-text">Прибытие:<br>{{train.end_date}}<br>{{train.end_time}}</p>
                    </div>
                </div>
                <div class="container-fluid">
                    <h5 class="card-title">Место</h5>
                    <p class="card-text">Отправление: {{train.start_city}}</p>
                    <p class="card-text">Прибытие: {{train.end_city}}</p>
                </div>
            </div>
            
            <a href="/train/{{train.slug}}" class="btn btn-danger">Купить</a>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h2 class="p-3">Нет поездов</h2>
    {% endif %}
</div>
{% endblock %}